import express from 'express'
import cors from 'cors'
import dotenv from 'dotenv'
import path from 'path'
import { fileURLToPath } from 'url'

// Imports matching your exact folder structure
import githubRoutes from './routes/github_api_routes.js'
import statsRoutes from './routes/stats_api_routes.js'

dotenv.config()

const app = express()
const PORT = process.env.PORT || 5000

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Middleware
app.use(cors())
app.use(express.json())

// API Routes
app.use('/api', githubRoutes)
app.use('/api', statsRoutes)

// Serve production assets generated by Vite (`dist`)
const frontendDistPath = path.join(__dirname, '../frontend/dist')
app.use(express.static(frontendDistPath))

// Express v5 wildcard catch-all route for React Router
app.get('/*splat', (req, res) => {
  res.sendFile(path.join(frontendDistPath, 'index.html'))
})

app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`)
})